### ISSUE TITLE
Setup consistently fails

### ISSUE THREAD

**Issue by estheranza** [Flowtter/crispy#12]
setup.bat consistently fails to build wheels for NumPy. Windows 11, python 3.10.6. Can't get the error message, the file closes when it fails to install. I think it said something to do with lapack atlas files missing. 
I apologize if this is not helpful or formatted incorrectly/in the wrong place, I don't really have any idea what I'm doing here, just noticed a bug/ incompatibility that completely breaks crispy.

**Comment by Flowtter** [comment]
Hello,

No problem, the issue could be windows 11, we didn't test on it.

What you can do is open a command prompt, navigate to the directory using `cd` and run the command
`pip install -r requirements.txt`

You'll have some logs that you can copy paste here or debug.

**Comment by liyunze-coding** [comment]
Some of the dependencies in `requirements.txt` seemed to be outdated, mainly NumPy and iPython

**Comment by Flowtter** [comment]
Yes we know.
Unfortunately they are necessaries for other libraries.
For example librosa requires numpy to not be above 1.3 if I remember correctly.

The problem is that we have a lot of dependencies that restrict our versions.

They are a few vulnerabilities in the current numpy and IPython and we plan on upgrading them as soon as the bottleneck from other libraries is released.

**Comment by estheranza** [comment]
I keep getting an error: NumPy 1.21.0 may not yet support Python 3.10. I also keep seeing that I am "missing blas and lapack"

**Comment by Flowtter** [comment]
The program has been created with python 3.8.10
Seems like 3.10 has issues indeed https://pullanswer.com/questions/python-3-10-6-for-windows-x86-is-missing-installed-blas-lapack

I updated the release, you can try to download it again and change the python version to 3.8.10

**Comment by estheranza** [comment]
Mine now works, I would recommend adding instructions on how to manually install the dependencies using pip if people are on the wrong version of python to the documentation. Thank you!

**Comment by TheRealS4MI** [comment]
![image](https://github.com/Flowtter/crispy/assets/140438050/bec5084e-c200-48fd-a1af-f92a2d94d0fc)
still not working was there a python update i missed?

**Comment by Flowtter** [comment]
This seems to be a totally different issue from reading the output log.
I would recommend double checking all the steps in the installation, you might have skipped one
