### ISSUE TITLE
Axios Error: Network Error

### ISSUE THREAD

**Issue by Zorral** [Flowtter/crispy#16]
After clicking on run.BAT, my cmd opens and shuts itself down within the span of a second, it's basically impossible to see what happened. I downloaded ffmpeg properly, and followed the other procedures, am I doing something wrong?

**Comment by Flowtter** [comment]
Unfortunately, I'll need more info to help you.
Start by re-running the setup.BAT.
Then, start a cmd, and using the `cd` command, navigate to the `crispy` folder.
After that run `python backend/src/app.py`.
If there is any error, report it here, otherwise, try to re-run the run.BAT.

**Comment by Zorral** [comment]
![image](https://user-images.githubusercontent.com/81542634/191394730-6012195f-7cf0-44bc-8a3b-74913dec9b0b.png)

I get this error despite opening up cmd with admin

**Comment by Flowtter** [comment]
Someone had the exact same issue.
The answer has been given on the [reddit thread](https://www.reddit.com/r/VALORANT/comments/x5x29x/i_used_machine_learning_to_help_me_analyse/?utm_medium=android_app&utm_source=share)

**Comment by Zorral** [comment]
Oh I'm so sorry, I fixed that issue! Thank you so much for the help.
