### ISSUE TITLE
merged.mp4 not showing up 

### ISSUE THREAD

**Issue by nepucchi** [Flowtter/crispy#17]
so after i extracted the zip, i ran the setup.bat and run.bat files as told in the instructions, but when i clicked on the results page after i selected my clips, it was just blank. When i checked my folder the merged.mp4 and merged.jpg files werent there either. Did i do something wrong during the installation? 
![image](https://user-images.githubusercontent.com/100029794/193163419-d84d9e7f-8eb1-48c3-a800-af57a3b7ab92.png)
![image](https://user-images.githubusercontent.com/100029794/193163443-dc692a88-cbe1-4c1d-ace0-b09c1fdd34a1.png)
![image](https://user-images.githubusercontent.com/100029794/193163590-79015362-5544-4394-b896-febafd6c0d8f.png)
first and second images show the cuts and results menu. Third image shows the exception.

**Comment by Flowtter** [comment]
This is indeed quite surprising.

Don't you have any other error when making the cuts ? 
Do tou have enough space on your pc ?
You're using mp4 files ?

Try to delete the "session folder" and the "tmp" one and retry

**Comment by nepucchi** [comment]
> This is indeed quite surprising.
> 
> Don't you have any other error when making the cuts ? Do tou have enough space on your pc ? You're using mp4 files ?
> 
> Try to delete the "session folder" and the "tmp" one and retry

1. i have tried running in multiple different drives and the result remains the same.
2. i have tried deleting session and tmp as well, to no avail.
as for errors when making the cuts, i noticed that the preview for the cuts dont show up at all, as shown in the screenshot i posted on the original thread.

**Comment by Flowtter** [comment]
This is indeed quite surprising, could you share some screenshots of what is inside the tmp folder ?

**Comment by nepucchi** [comment]
> This is indeed quite surprising, could you share some screenshots of what is inside the tmp folder ?

![image](https://user-images.githubusercontent.com/100029794/193401605-b6002551-c814-421c-a3c6-196859bae17c.png)
![image](https://user-images.githubusercontent.com/100029794/193401620-f30cf18c-4a0f-4eee-b260-dac66c50d0be.png)
![image](https://user-images.githubusercontent.com/100029794/193401621-2fb8008b-3f2d-40ed-8263-e3b595722214.png)
![image](https://user-images.githubusercontent.com/100029794/193401630-a06daff6-c90c-4749-8f63-b80ee9641a5d.png)
![image](https://user-images.githubusercontent.com/100029794/193401641-27d22390-414a-4b88-8bf5-8807b6c8bda1.png)

the images above shows whats inside my tmp folder, as well as the contents of the folder of the individual clips and the json file.

**Comment by Flowtter** [comment]
I think that the machine learning algorithm.
Can you try to decrease the [confidence](https://github.com/Flowtter/crispy/blob/master/settings.json) to **0.4**, just to be sure ?

**Comment by nepucchi** [comment]
> I think that the machine learning algorithm do not detect any kills. Can you try to decrease the [confidence](https://github.com/Flowtter/crispy/blob/master/settings.json) to **0.4**, just to be sure ?

i tried 0.3 and 0.4 and it is still the same. Would having a stretched resolution affect the algorithm somehow? since all the clips that i used are in 4:3.
![image](https://user-images.githubusercontent.com/100029794/193402787-df95648a-750d-41f6-9f50-004e4405c3e1.png)
![image](https://user-images.githubusercontent.com/100029794/193402796-b535e4ef-8841-4a02-80b5-4e256ef35a11.png)

**Comment by nepucchi** [comment]
okay, i think i found the issue. I tried using my friend's clip that uses 16:9 and the code is running as intended. I think having a reso other than 16:9 messes with the algorithm somehow. Is there any way around this?

**Comment by Flowtter** [comment]
> since all the clips that i used are in 4:3
Unfortunately yes.
The AI probably can't recognize the highlights because of it.
There isn't also any workaround at the moment.
If you've the time, you can train a network. But It is quite tedious.

**Comment by nepucchi** [comment]
ah okay then. Thanks a bunch for helping out, but i have neither the time nor the knowledge for it haha. I'll close the thread then

**Comment by Flowtter** [comment]
Hi @nepucchi, hope you're doing well.

This has been fixed in https://github.com/Flowtter/crispy/pull/43 ! 

Hope you'll give it a try
