### ISSUE TITLE
Unable to Identify and Create Segments with non-standard resolutions and Modified HUD positions

### ISSUE THREAD

**Issue by MarcoColomb0** [Flowtter/crispy#41]
### Steps to Reproduce:
Use a resolution different from 1920x1080 (16:9), for example, I'm using 1280x960 (4:3).

### Expected Behavior:
Segments should still be created on different resolutions.

### Observed Behavior:
The segments work fine on 1920x1080 resolution without any issues. However, when using a different resolution like 1280x960, the generated images in the "/sessions" folder are not positioned correctly, and the model is unable to identify game actions.

### Environment:
Operating System: Windows 10 - 22H2
Python Version: 3.8

### Attempts to Resolve:
I attempted to modify values in "/api/models/highlight.py" to correctly center the images, but the model still couldn't identify the segments. This could be due to the different aspect ratio between the resolutions.

Thank you.

Snapshot from one of my clips (HUD position showcase):
![snapshot](https://github.com/Flowtter/crispy/assets/127960315/b8e9c018-b3de-488a-8e6b-a0f8b4888efa)

**Comment by MarcoColomb0** [comment]
Hello Brice,

CS2 allows you to edit the HUD position under Settings > Video > HUD Edge Positions, and it is not caused by the different resolution. 

![HUDEdgePositions](https://github.com/Flowtter/crispy/assets/127960315/c0f25bbe-9589-44a5-b3b2-1e6e0cc6fbf3)

That's why there's more spacing on the HUD borders in my screenshot. It's a personal preference, and I would prefer not to change my in-game config as I've been using the same settings since CS:GO.

Another thing I would like to understand is that I'm using 1280x960 (stretched), but my clips on ShadowPlay are getting encoded in 1920x1080. I'm doing this so the clips are already stretched, and I don't have to manually stretch them in an editing program. Could this be a problem for the network to identify segments? I guess modifying parameters for [this resizing feature](https://github.com/Flowtter/crispy/blob/master/crispy-api/api/tools/setup.py#L96L102) is not necessary, as the clips are already 1920x1080.

Please let me know if I'm wrong, and thank you for the help :)

**Comment by Flowtter** [comment]
Hi Marco,

I was unaware of the possibility to edit the HUD. That is totally my bad. I'll deploy a fix this month.

In the meantime this should totally work, being in 4:3 or 16:9 will not make a difference
> by adjusting the position of the cropped box, which can be done [here](https://github.com/Flowtter/crispy/blob/61fa06ec4391ccf27175950dcfac1c789c13d49d/crispy-api/api/models/highlight.py#L177L179). It should align with the typical cropping section. You can experiment with a standard 1080p gameplay to find the correct position; a simple translation along the height axis should suffice.

But because you're on a stretch resolution, don't forget to lower the confidence.

Overall, this should fix your issue:
> I genuinely believe that modifying the position of the cropped box and [reducing the confidence level](https://github.com/Flowtter/crispy/blob/master/crispy-api/settings.json#L3) should resolve the issue.


As for your question with ShadowPlay, I don't think it will create an issue.

**Comment by Flowtter** [comment]
Hi Marco,

I'm having some problems with all the customizations available on CS. I wasn't expecting [you can change size, color and position] (https://www.youtube.com/watch?v=C5VuTPW8Xk8).

That seems to be a lot for the current crispy.

I could fix the position, but that wouldn't satisfy the color and size.

I'll try to find a solution when I have the time.

**Comment by Flowtter** [comment]
Hello Marco, I hope you're doing well!

I couldn't find a perfect solution for CS2. A few months ago, I was working on a LoL version, and I believe it could assist me in understanding the problem with CS2 better. However, currently, I'm not actively working on it.

Regarding your Valorant issue, the main problem with stretch resolution is that Crispy is converting it to [1080p](https://github.com/Flowtter/crispy/blob/61fa06ec4391ccf27175950dcfac1c789c13d49d/crispy-api/api/tools/setup.py#L96-L97).

This conversion is necessary to ensure the image is the right size for the AI. The crucial aspect is maintaining the same height and width for the kill-circle as in the footage it was trained on.

Now, I have an idea that might work.

If we calculate the height ratio (3:4) and apply it to the width (1920 * 0.75 = 1440), we get a resolution that the AI might be able to work with. This way, we'll have a kill circle of the perfect size, though not at the right place.

Your image would look like this:
![image](https://github.com/Flowtter/crispy/assets/34689945/5248dadd-7fa1-4e07-b651-8b2c0870325a)
(resolution 1440x1080)

To achieve this, simply apply a Pillow filter [here](https://github.com/Flowtter/crispy/blob/61fa06ec4391ccf27175950dcfac1c789c13d49d/crispy-api/api/models/highlight.py#L88) that resizes the image as done [here](https://github.com/Flowtter/crispy/blob/61fa06ec4391ccf27175950dcfac1c789c13d49d/crispy-api/api/tools/setup.py#L96-L97).

Now, if you change the first value [here](https://github.com/Flowtter/crispy/blob/61fa06ec4391ccf27175950dcfac1c789c13d49d/crispy-api/api/models/highlight.py#L161C9-L163C10) from 899 to 660 (you can test between 658 to 662 to find the best fit), which should be the first coordinate of the box, you might have a solution.

I haven't tested it, so please let me know if it works for you!

If it does, please inform me, and we can consider making a pull request, either by you or me. This would be a great first contribution! ;)

**Comment by MarcoColomb0** [comment]
I tried doing what you suggested, but I think I made something wrong (I'm not a Python expert or anything 🤣).
The images with the mask look like this.
![00000183](https://github.com/Flowtter/crispy/assets/127960315/72eadd1a-4d5e-4d97-8af6-f7b406111ebc)
I honestly don't know.

**Comment by Flowtter** [comment]
Hey Marco,
I made it work !
The fix I gave you earlier could not work, that was my bad.
Here is the complete diff:

```diff
index c9b0a34..2e976b4 100644
--- a/crispy-api/api/models/highlight.py
+++ b/crispy-api/api/models/highlight.py
@@ -159,7 +159,7 @@ class Highlight(Thingy):
             return final
 
         return await self.extract_images(
-            post_process, (899, 801, 122, 62), framerate=framerate
+            post_process, (660, 801, 122, 62), framerate=framerate
         )
 
     async def extract_csgo2_images(self, framerate: int = 4) -> bool:
diff --git a/crispy-api/api/tools/setup.py b/crispy-api/api/tools/setup.py
index b45ed94..a2df5fc 100644
--- a/crispy-api/api/tools/setup.py
+++ b/crispy-api/api/tools/setup.py
@@ -93,8 +93,8 @@ async def handle_highlights(
             ).overwrite_output().run()
             shutil.move(tmp_path, highlight.path)
 
-        if Image.open(highlight.thumbnail_path_full_size).size != (1920, 1080):
-            await highlight.scale_video()
+        if Image.open(highlight.thumbnail_path_full_size).size != (1440, 1080):
+            await highlight.scale_video(1440, 1080)
             coroutines = [
                 highlight.extract_thumbnails(),
                 highlight.extract_snippet_in_lower_resolution(),
```

I basically moved the box to the left, and resized the video to the right size earlier !
I tried on the screenshot you provided with Reyna and it works.

**Comment by MarcoColomb0** [comment]
That's not working for me 😢 
Some of my clips are recorded in this size, for example: 
![image](https://github.com/Flowtter/crispy/assets/127960315/5a8d736a-31ae-41b4-986b-a3202162deb2)
I think I still have something to tweak, considering my in-game resolution of 1280x960

**Comment by Flowtter** [comment]
Could you send me the clip ? You can just upload it there or if it doesn't work, on youtube

**Comment by Flowtter** [comment]
Hi Marco,

I created a PR that should solve your issue.
https://github.com/Flowtter/crispy/pull/43

Let me know if you have any issues, I'll merge it next week
