### ISSUE TITLE
pip is not recognized

### ISSUE THREAD

**Issue by SomeJoestar** [Flowtter/crispy#45]
![image_2024-02-06_013149519](https://github.com/Flowtter/crispy/assets/159089885/6adc00af-5c82-4078-b6c5-cd46c4563a45)

hey when i start the setup batch file this comes up pressing any key crashes it instantly, i appreciate any help

**Comment by Flowtter** [comment]
Hi,
pip comes with/from python.
It is *probably* an issue with the installation of python.
Either it is not in your $PATH or it has not been installed properly.
[This should do the job](https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/#:~:text=Reinstall%20Python%20to%20Fix%20'Pip,components%20to%20fix%20the%20problem).

**Comment by SomeJoestar** [comment]
![image](https://github.com/Flowtter/crispy/assets/159089885/c8f67ba0-6cc5-4e7a-937b-63fddfd36878)
reinstalled it like the site said and now this error pops up

**Comment by Flowtter** [comment]
I think, [python 3.12 removing distutils](https://peps.python.org/pep-0632/) make crispy unstable.
Could you try [any of those versions ?](https://github.com/Flowtter/crispy/blob/master/.github/workflows/pytest.yml#L18)

**Comment by SomeJoestar** [comment]
the setup seems to be completeted, after pressing run i get a axioserror but it only says warning wait for application startup complete to use crispy so i think i have to wait?

**Comment by Flowtter** [comment]
Yes, you should wait for the API to be ready (the black window / cmd), then you can refresh your browser tab.

**Comment by SomeJoestar** [comment]
alright perfect i,ll close the issue as soon as the api is ready i´ll leave it open until then just incase another error occures or it infinitly loads
