### ISSUE TITLE
setup.bat error windows 11

### ISSUE THREAD

**Issue by reinardphilip** [Flowtter/crispy#50]
C:\Users\philip\Downloads\windows\windows>pip install -Ir requirements.txt
Collecting https://github.com/Refty/thingy/archive/bb8565a25a428b1d607aa65111552fb3e12f2a12.zip (from -r requirements.txt (line 3))
  Using cached https://github.com/Refty/thingy/archive/bb8565a25a428b1d607aa65111552fb3e12f2a12.zip
  Preparing metadata (setup.py) ... done
Collecting https://github.com/Refty/mongo-thingy/archive/0e32be38391b2ed4b369641996384eb94be60c7c.zip (from -r requirements.txt (line 6))
  Using cached https://github.com/Refty/mongo-thingy/archive/0e32be38391b2ed4b369641996384eb94be60c7c.zip
  Preparing metadata (setup.py) ... done
Collecting fastapi==0.75.2 (from -r requirements.txt (line 8))
  Using cached fastapi-0.75.2-py3-none-any.whl.metadata (24 kB)
Collecting python-multipart==0.0.5 (from -r requirements.txt (line 9))
  Using cached python-multipart-0.0.5.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting uvicorn==0.17.6 (from -r requirements.txt (line 10))
  Using cached uvicorn-0.17.6-py3-none-any.whl.metadata (6.2 kB)
Collecting python-dotenv==0.10.3 (from -r requirements.txt (line 11))
  Using cached python_dotenv-0.10.3-py2.py3-none-any.whl.metadata (15 kB)
Collecting motor==3.1.1 (from -r requirements.txt (line 12))
  Using cached motor-3.1.1-py3-none-any.whl.metadata (7.3 kB)
Collecting ffmpeg-python==0.2.0 (from -r requirements.txt (line 15))
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Collecting Pillow==9.4.0 (from -r requirements.txt (line 16))
  Using cached Pillow-9.4.0.tar.gz (50.4 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.24.1 (from -r requirements.txt (line 17))
  Using cached numpy-1.24.1.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\philip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\philip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\philip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\philip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\philip\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\philip\AppData\Local\Temp\pip-build-env-l3k0mj0c\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\philip\AppData\Local\Temp\pip-build-env-l3k0mj0c\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\philip\AppData\Local\Temp\pip-build-env-l3k0mj0c\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Users\philip\Downloads\windows\windows>pause

**Comment by Flowtter** [comment]
Hi the [python version you are using is not supported](https://github.com/Flowtter/crispy?tab=readme-ov-file#python-version).
Try with python 3.10.

**Comment by reinardphilip** [comment]
> Hi the [python version you are using is not supported](https://github.com/Flowtter/crispy?tab=readme-ov-file#python-version). Try with python 3.10.

heyy so now the setup.bat file worked with no errors but another problem is it says AxiosError: NetworkError or something like that and the clips is not in the website even tho i put it in the resources > video folder and yes it is mp4

**Comment by Flowtter** [comment]
You must wait for the backend to be ready.
The setup.bat opens a tab in your navigator and a cmd (black window), wait for the cmd to tell you that it is ready and refresh your navigator's tab.

**Comment by reinardphilip** [comment]
hey it says press any key to continue and it did no errors then i run the run.bat and it still says AxiosError: NetworkError. i dont know what im doing wrong

**Comment by Flowtter** [comment]
Hi,
Can you screenshot the CMD ?

**Comment by reinardphilip** [comment]
hey uhm my run.bat suddenly wont work and it says fronten/index.html wasnt showing in a result or something like that

**Comment by reinardphilip** [comment]
C:\Users\philip\Desktop\windows>pip install -Ir requirements.txt
Collecting https://github.com/Refty/thingy/archive/bb8565a25a428b1d607aa65111552fb3e12f2a12.zip (from -r requirements.txt (line 3))
  Using cached https://github.com/Refty/thingy/archive/bb8565a25a428b1d607aa65111552fb3e12f2a12.zip
  Preparing metadata (setup.py) ... done
Collecting https://github.com/Refty/mongo-thingy/archive/0e32be38391b2ed4b369641996384eb94be60c7c.zip (from -r requirements.txt (line 6))
  Using cached https://github.com/Refty/mongo-thingy/archive/0e32be38391b2ed4b369641996384eb94be60c7c.zip
  Preparing metadata (setup.py) ... done
Collecting fastapi==0.75.2 (from -r requirements.txt (line 8))
  Using cached fastapi-0.75.2-py3-none-any.whl.metadata (24 kB)
Collecting python-multipart==0.0.5 (from -r requirements.txt (line 9))
  Using cached python_multipart-0.0.5-py3-none-any.whl
Collecting uvicorn==0.17.6 (from -r requirements.txt (line 10))
  Using cached uvicorn-0.17.6-py3-none-any.whl.metadata (6.2 kB)
Collecting python-dotenv==0.10.3 (from -r requirements.txt (line 11))
  Using cached python_dotenv-0.10.3-py2.py3-none-any.whl.metadata (15 kB)
Collecting motor==3.1.1 (from -r requirements.txt (line 12))
  Using cached motor-3.1.1-py3-none-any.whl.metadata (7.3 kB)
Collecting ffmpeg-python==0.2.0 (from -r requirements.txt (line 15))
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Collecting Pillow==9.4.0 (from -r requirements.txt (line 16))
  Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl.metadata (9.4 kB)
Collecting numpy==1.24.1 (from -r requirements.txt (line 17))
  Using cached numpy-1.24.1-cp310-cp310-win_amd64.whl.metadata (5.6 kB)
Collecting moviepy==1.0.3 (from -r requirements.txt (line 18))
  Using cached moviepy-1.0.3-py3-none-any.whl
Collecting progressbar2==4.0.0 (from -r requirements.txt (line 19))
  Using cached progressbar2-4.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting scipy==1.8.0 (from -r requirements.txt (line 20))
  Using cached scipy-1.8.0-cp310-cp310-win_amd64.whl.metadata (2.2 kB)
Collecting pydub==0.25.1 (from -r requirements.txt (line 21))
  Using cached pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting montydb==2.4.0 (from -r requirements.txt (line 22))
  Using cached montydb-2.4.0-py3-none-any.whl.metadata (10.0 kB)
Collecting easyocr==1.7.1 (from -r requirements.txt (line 23))
  Using cached easyocr-1.7.1-py3-none-any.whl.metadata (11 kB)
Collecting starlette==0.17.1 (from fastapi==0.75.2->-r requirements.txt (line 8))
  Using cached starlette-0.17.1-py3-none-any.whl.metadata (6.3 kB)
Collecting pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 (from fastapi==0.75.2->-r requirements.txt (line 8))
  Using cached pydantic-1.10.15-cp310-cp310-win_amd64.whl.metadata (152 kB)
Collecting six>=1.4.0 (from python-multipart==0.0.5->-r requirements.txt (line 9))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting asgiref>=3.4.0 (from uvicorn==0.17.6->-r requirements.txt (line 10))
  Using cached asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting click>=7.0 (from uvicorn==0.17.6->-r requirements.txt (line 10))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting h11>=0.8 (from uvicorn==0.17.6->-r requirements.txt (line 10))
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pymongo<5,>=4.1 (from motor==3.1.1->-r requirements.txt (line 12))
  Using cached pymongo-4.7.0-cp310-cp310-win_amd64.whl.metadata (22 kB)
Collecting future (from ffmpeg-python==0.2.0->-r requirements.txt (line 15))
  Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting decorator<5.0,>=4.0.2 (from moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached decorator-4.4.2-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting tqdm<5.0,>=4.11.2 (from moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
Collecting requests<3.0,>=2.8.1 (from moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting proglog<=1.0.0 (from moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached proglog-0.1.10-py3-none-any.whl.metadata (639 bytes)
Collecting imageio<3.0,>=2.5 (from moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached imageio-2.34.1-py3-none-any.whl.metadata (4.9 kB)
Collecting imageio-ffmpeg>=0.2.0 (from moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting python-utils>=3.0.0 (from progressbar2==4.0.0->-r requirements.txt (line 19))
  Using cached python_utils-3.8.2-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting torch (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached torch-2.3.0-cp310-cp310-win_amd64.whl.metadata (26 kB)
Collecting torchvision>=0.5 (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached torchvision-0.18.0-cp310-cp310-win_amd64.whl.metadata (6.6 kB)
Collecting opencv-python-headless (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting scikit-image (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached scikit_image-0.23.2-cp310-cp310-win_amd64.whl.metadata (14 kB)
Collecting python-bidi (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached python_bidi-0.4.2-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting PyYAML (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
Collecting Shapely (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached shapely-2.0.4-cp310-cp310-win_amd64.whl.metadata (7.2 kB)
Collecting pyclipper (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached pyclipper-1.3.0.post5-cp310-cp310-win_amd64.whl.metadata (9.2 kB)
Collecting ninja (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
Collecting anyio<4,>=3.0.0 (from starlette==0.17.1->fastapi==0.75.2->-r requirements.txt (line 8))
  Using cached anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting typing-extensions>=4 (from asgiref>=3.4.0->uvicorn==0.17.6->-r requirements.txt (line 10))
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama (from click>=7.0->uvicorn==0.17.6->-r requirements.txt (line 10))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting setuptools (from imageio-ffmpeg>=0.2.0->moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo<5,>=4.1->motor==3.1.1->-r requirements.txt (line 12))
  Using cached dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0,>=2.8.1->moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0,>=2.8.1->moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0,>=2.8.1->moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.8.1->moviepy==1.0.3->-r requirements.txt (line 18))
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting filelock (from torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached filelock-3.13.4-py3-none-any.whl.metadata (2.8 kB)
Collecting sympy (from torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached sympy-1.12-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting fsspec (from torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting mkl<=2021.4.0,>=2021.1.1 (from torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.4 kB)
INFO: pip is looking at multiple versions of scikit-image to determine which version is compatible with other requirements. This could take a while.
Collecting scikit-image (from easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached scikit_image-0.23.1-cp310-cp310-win_amd64.whl.metadata (14 kB)
  Using cached scikit_image-0.22.0-cp310-cp310-win_amd64.whl.metadata (13 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached tifffile-2024.4.24-py3-none-any.whl.metadata (31 kB)
Collecting packaging>=21 (from scikit-image->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting lazy_loader>=0.3 (from scikit-image->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Collecting sniffio>=1.1 (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi==0.75.2->-r requirements.txt (line 8))
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting exceptiongroup (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi==0.75.2->-r requirements.txt (line 8))
  Using cached exceptiongroup-1.2.1-py3-none-any.whl.metadata (6.6 kB)
Collecting intel-openmp==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.2 kB)
Collecting tbb==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached tbb-2021.12.0-py3-none-win_amd64.whl.metadata (1.1 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Collecting mpmath>=0.19 (from sympy->torch->easyocr==1.7.1->-r requirements.txt (line 23))
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached fastapi-0.75.2-py3-none-any.whl (54 kB)
Using cached uvicorn-0.17.6-py3-none-any.whl (53 kB)
Using cached python_dotenv-0.10.3-py2.py3-none-any.whl (16 kB)
Using cached motor-3.1.1-py3-none-any.whl (56 kB)
Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
Using cached numpy-1.24.1-cp310-cp310-win_amd64.whl (14.8 MB)
Using cached progressbar2-4.0.0-py2.py3-none-any.whl (26 kB)
Using cached scipy-1.8.0-cp310-cp310-win_amd64.whl (37.0 MB)
Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Using cached montydb-2.4.0-py3-none-any.whl (74 kB)
Using cached easyocr-1.7.1-py3-none-any.whl (2.9 MB)
Using cached starlette-0.17.1-py3-none-any.whl (58 kB)
Using cached asgiref-3.8.1-py3-none-any.whl (23 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached imageio-2.34.1-py3-none-any.whl (313 kB)
Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl (22.6 MB)
Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Using cached pydantic-1.10.15-cp310-cp310-win_amd64.whl (2.1 MB)
Using cached pymongo-4.7.0-cp310-cp310-win_amd64.whl (484 kB)
Using cached python_utils-3.8.2-py2.py3-none-any.whl (27 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached torchvision-0.18.0-cp310-cp310-win_amd64.whl (1.2 MB)
Using cached torch-2.3.0-cp310-cp310-win_amd64.whl (159.8 MB)
Using cached tqdm-4.66.2-py3-none-any.whl (78 kB)
Using cached future-1.0.0-py3-none-any.whl (491 kB)
Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Using cached pyclipper-1.3.0.post5-cp310-cp310-win_amd64.whl (108 kB)
Using cached python_bidi-0.4.2-py2.py3-none-any.whl (30 kB)
Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
Using cached scikit_image-0.22.0-cp310-cp310-win_amd64.whl (24.5 MB)
Using cached shapely-2.0.4-cp310-cp310-win_amd64.whl (1.4 MB)
Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Using cached dnspython-2.6.1-py3-none-any.whl (307 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
Using cached tbb-2021.12.0-py3-none-win_amd64.whl (286 kB)
Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Using cached tifffile-2024.4.24-py3-none-any.whl (225 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached filelock-3.13.4-py3-none-any.whl (11 kB)
Using cached fsspec-2024.3.1-py3-none-any.whl (171 kB)
Using cached Jinja2-3.1.3-py3-none-any.whl (133 kB)
Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Using cached MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
Building wheels for collected packages: Thingy, Mongo-Thingy
  Building wheel for Thingy (setup.py) ... done
  Created wheel for Thingy: filename=Thingy-0.9.0-py3-none-any.whl size=4577 sha256=dc05f7b5c55f1da0ed08fcfcdaca6e2f211968ad0216236f5f33885e115863c1
  Stored in directory: C:\Users\philip\AppData\Local\Temp\pip-ephem-wheel-cache-9bzr88ly\wheels\dc\0d\1e\64fe6c788a1c21b9a2cee8e4c37e430ba0cda5f01825a32ee9
  Building wheel for Mongo-Thingy (setup.py) ... done
  Created wheel for Mongo-Thingy: filename=Mongo_Thingy-0.15.1-py3-none-any.whl size=9680 sha256=c0611ae7e27be66b440672a87dcd65c8def215902a654442dc739c6597513baa
  Stored in directory: C:\Users\philip\AppData\Local\Temp\pip-ephem-wheel-cache-9bzr88ly\wheels\23\2b\6d\f533fcd3c2595eebd816752eda31a118da316a984f7a2d7557
Successfully built Thingy Mongo-Thingy
Installing collected packages: Thingy, tbb, python-dotenv, pydub, pyclipper, ninja, mpmath, intel-openmp, urllib3, typing-extensions, sympy, sniffio, six, setuptools, PyYAML, Pillow, packaging, numpy, networkx, montydb, mkl, MarkupSafe, idna, h11, future, fsspec, filelock, exceptiongroup, dnspython, decorator, colorama, charset-normalizer, certifi, tqdm, tifffile, Shapely, scipy, requests, python-utils, python-multipart, python-bidi, pymongo, pydantic, opencv-python-headless, lazy_loader, jinja2, imageio-ffmpeg, imageio, ffmpeg-python, click, asgiref, anyio, uvicorn, torch, starlette, scikit-image, progressbar2, proglog, motor, Mongo-Thingy, torchvision, moviepy, fastapi, easyocr
Successfully installed MarkupSafe-2.1.5 Mongo-Thingy-0.15.1 Pillow-9.4.0 PyYAML-6.0.1 Shapely-2.0.4 Thingy-0.9.0 anyio-3.7.1 asgiref-3.8.1 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 decorator-4.4.2 dnspython-2.6.1 easyocr-1.7.1 exceptiongroup-1.2.1 fastapi-0.75.2 ffmpeg-python-0.2.0 filelock-3.13.4 fsspec-2024.3.1 future-1.0.0 h11-0.14.0 idna-3.7 imageio-2.34.1 imageio-ffmpeg-0.4.9 intel-openmp-2021.4.0 jinja2-3.1.3 lazy_loader-0.4 mkl-2021.4.0 montydb-2.4.0 motor-3.1.1 moviepy-1.0.3 mpmath-1.3.0 networkx-3.3 ninja-1.11.1.1 numpy-1.24.1 opencv-python-headless-4.9.0.80 packaging-24.0 proglog-0.1.10 progressbar2-4.0.0 pyclipper-1.3.0.post5 pydantic-1.10.15 pydub-0.25.1 pymongo-4.6.3 python-bidi-0.4.2 python-dotenv-0.10.3 python-multipart-0.0.5 python-utils-3.8.2 requests-2.31.0 scikit-image-0.22.0 scipy-1.8.0 setuptools-57.4.0 six-1.16.0 sniffio-1.3.1 starlette-0.17.1 sympy-1.12 tbb-2021.12.0 tifffile-2024.4.18 torch-2.2.2 torchvision-0.17.2 tqdm-4.66.2 typing-extensions-4.11.0 urllib3-2.2.1 uvicorn-0.17.6

C:\Users\philip\Desktop\windows>pause
Press any key to continue . . .

this is the cmd of my setup.bat

**Comment by Flowtter** [comment]
> hey uhm my run.bat suddenly wont work and it says fronten/index.html wasnt showing in a result or something like that

I cant help you if you don't provide screenshots or the exact error :(

Please re-download the project, run the `run.bat` and screenshot the CMD

**Comment by reinardphilip** [comment]
![image](https://github.com/Flowtter/crispy/assets/114043833/982ce615-8f86-4ca2-bfa9-883d1064110d)

**Comment by reinardphilip** [comment]
> > hey uhm my run.bat suddenly wont work and it says fronten/index.html wasnt showing in a result or something like that
> 
> I cant help you if you don't provide screenshots or the exact error :(
> 
> Please re-download the project, run the `run.bat` and screenshot the CMD

i can screenshot it because it just closes so quickly, i once ran it with administrator and it just says frontend/index.html was not found or something like that

**Comment by reinardphilip** [comment]
![image](https://github.com/Flowtter/crispy/assets/114043833/9dd220bf-2cd4-45b8-a573-27f0f8b4f188)
this happens

**Comment by Flowtter** [comment]
It is because you are in the wrong directory. You have to use the `cd` command to move into your download folder and then crispy.

You can search on google if you don't know how to use cd.
Then you will be able to `start frontend/index.html`.
But this only start the navigator tab.

What you want is to run the backend

So `cd` first where crispy is located and run `python -m api`

**Comment by reinardphilip** [comment]
![image](https://github.com/Flowtter/crispy/assets/114043833/cb9bee71-f174-4d57-8267-993f1445a7d2)

this happens

**Comment by reinardphilip** [comment]
![image](https://github.com/Flowtter/crispy/assets/114043833/1018537d-80ac-4b1b-b04f-079e03b01ec4)
and also this when i want to start the frontend

**Comment by reinardphilip** [comment]
hey so i tried opening up the index myself and it didnt even direct me to any web and it just popped and closed a cmd so quick that i cant see

**Comment by reinardphilip** [comment]
![image](https://github.com/Flowtter/crispy/assets/114043833/c6548173-0a8d-4d1b-9940-9125fe901706)

**Comment by reinardphilip** [comment]
can someone help
pls

**Comment by Flowtter** [comment]
> ![image](https://private-user-images.githubusercontent.com/114043833/326231347-c6548173-0a8d-4d1b-9940-9125fe901706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTUzMDYsIm5iZiI6MTcxNDMxNTAwNiwicGF0aCI6Ii8xMTQwNDM4MzMvMzI2MjMxMzQ3LWM2NTQ4MTczLTBhOGQtNGQxYi05OTQwLTkxMjVmZTkwMTcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNDM2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjdkMmY1YWVlYWUyY2U1MjdlZTkxZWJkM2M5Y2EyNzQ0ZWU1YTE3MzMyNTQ0NTQ5MzNjMTlmNmIxOThkMDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nWG6fN_S4CwJs_XE_EioUnahHY87wN1_pJ1xUN65PrY)

You should be able to open crispy in your browser then, the backend started correctly. Maybe you have to refresh the page but that should be working.
