### ISSUE TITLE
I always get an error on the frontend web!

### ISSUE THREAD

**Issue by Slowing4356** [Flowtter/crispy#52]
I don't know what i should do, please help!

![image](https://github.com/user-attachments/assets/f8ce77b7-df6b-4317-b635-acdaa9635e83)
![image](https://github.com/user-attachments/assets/eb6a5bfb-7e65-44b0-b2cd-596006a0314f)

**Comment by Flowtter** [comment]
Hi,

The frontend cannot connect to the backend.

Can you screenshot the backend output ?

**Comment by Slowing4356** [comment]
Yes, how should i install ffmpeg, because i thought i have it already installed.
![image](https://github.com/user-attachments/assets/c84481a3-3deb-4085-ac41-23f390bee297)

**Comment by Slowing4356** [comment]
I've changed the drive and now i get this error.

![image](https://github.com/user-attachments/assets/e01439e6-a5e9-4889-90a2-af019afdc9f1)

**Comment by Slowing4356** [comment]
I've managed to fix it, I had "ffmpeg" **AND** "ffmpeg-python" installed, so i did this.

`pip uninstall ffmpeg
pip uninstall ffmpeg-python

pip install ffmpeg`
