### ISSUE TITLE
No backend folder and AxiosError: Network Error

### ISSUE THREAD

**Issue by jayranj** [Flowtter/crispy#54]
After seemingly running the setup successfully and not getting any errors, I still don't have a "backend" folder as seen in the demonstration videos.
Furthermore, probably as a result, when opening the run file, I get the AxiosError: Network Error.

Do I need to run the setup as admin? Because when I do, I then get this error:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

I looked all former issues and tried to implement their solutions but still couldn't manage to solve my problem.

Please bear with me, as i am kind of a layman when it comes to CS.

**Comment by Flowtter** [comment]
Hi,
No worries we'll have a look together.

Regarding the axios error, it is normal it is failing if the backend is not started!

From what I understand your zip might be incomplete since you have neither the requirements.txt and the backend folder.

Can you redownload the zip folder, extract in a new folder, and screenshot the result please ?

**Comment by jayranj** [comment]
So I did as you said and redownloaded and extracted the regular windows release into a folder.
![Screenshot 2024-08-23 144715](https://github.com/user-attachments/assets/1c3275f9-a48c-4762-86d4-bfe9aa5ebfdd)

It looks 1:1 as it did before with no backend folder but with the requirements.txt. That is why the error:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
was weird when the file was in fact in the folder.

**Comment by jayranj** [comment]
So i found the solution and it is actually kind of funny.

The solution was to install Microsoft Visual Studio. lol
