### ISSUE TITLE
No backend folder, AxiosError

### ISSUE THREAD

**Issue by Viliusas123** [Flowtter/crispy#55]
Hi, everything loads and it says ctrl c and when i press it it closes the cmd and it doenst connect to the backend and  the AxiosError still pops up.
![image_2024-09-17_213501576](https://github.com/user-attachments/assets/8b34090c-f76a-4396-a7cc-cbfda8a3fb0c)
![image_2024-09-17_213515903](https://github.com/user-attachments/assets/3fc725dc-8323-4362-be28-8fe5cec40d6b)
![image_2024-09-17_213601425](https://github.com/user-attachments/assets/370c4343-3794-454d-83cb-d2cff6708ee1)

**Comment by Flowtter** [comment]
![image](https://github.com/user-attachments/assets/05b8e848-3794-4dc1-8145-156b7d962366)
