### ISSUE TITLE
axios:network error

### ISSUE THREAD

**Issue by Darkemimence** [Flowtter/crispy#56]
I can't see any of my video files and when I open the setup file it says to press a random key which I do and it closes?
![image](https://github.com/user-attachments/assets/41e8f058-e7d2-4ace-adfc-5afe80c0573f)

**Comment by Flowtter** [comment]
Refer to the video and to the other similar [issues](https://github.com/Flowtter/crispy/issues?q=is%3Aissue+error).

**Comment by Darkemimence** [comment]
> Refer to the video and to the other similar [issues](https://github.com/Flowtter/crispy/issues?q=is%3Aissue+error).

Which video?

**Comment by Flowtter** [comment]
The [video](https://www.youtube.com/watch?v=svT-Z_MkAfw)is in the README.
