### ISSUE TITLE
ERROR:    Application startup failed. Exiting.

### ISSUE THREAD

**Issue by ayodkay** [Flowtter/crispy#58]
![image](https://github.com/user-attachments/assets/f099948f-051c-4bd3-b37b-82b2fd226b54)

**Comment by Flowtter** [comment]
Interesting, could you show the ffmpeg error log ?

**Comment by ayodkay** [comment]
the video i was trying to use got corrupted that is why i got this error. works perfectly now.

**Comment by Flowtter** [comment]
Thank you, I'll try to replicate it to log the error better in the future.

Thanks again for using crispy!
