### ISSUE TITLE
crispy downscales resource footages from 1440p to 1080

### ISSUE THREAD

**Issue by andyl11375** [Flowtter/crispy#59]
When using 1440p footage, the video is downscaled during pre-process to 1080p. Is it possible to omit this process in settings.json?

**Comment by Flowtter** [comment]
Hello and thanks for using crispy!

Unfortunately this is not possible for the moment, this is one of the limitation of the AI, it's only trained on 1080p.

**Comment by andyl11375** [comment]
This makes sense. Thanks for explanation.
